### **Задание на повторение материала

#### 1. 
Создать одномерный массив Numpy под названием a из 12 последовательных чисел чисел от 12 до 24 невключительно.

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2. 
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [3]:
a.reshape(1, 12)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [4]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [5]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [6]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [7]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### 3. 
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [8]:
a.reshape(1, -1)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [9]:
a.reshape(2, -1)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [10]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

#### 4. 
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [13]:
b = a.reshape(12, 1)

In [14]:
b.ndim

2

##### Ответ: нет

#### 5. 
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [15]:
c = np.random.randn(3, 4)
c

array([[-1.30125745, -0.96329816, -1.43737511,  0.20243099],
       [-0.94262815,  0.5991773 , -0.2480457 , -1.86246963],
       [ 1.05600337,  0.95533906,  2.80418234, -0.09235647]])

In [16]:
c.size

12

In [17]:
d = c.flatten()
d

array([-1.30125745, -0.96329816, -1.43737511,  0.20243099, -0.94262815,
        0.5991773 , -0.2480457 , -1.86246963,  1.05600337,  0.95533906,
        2.80418234, -0.09235647])

In [18]:
d.ndim

1

In [19]:
d.size

12

#### 6. 
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [20]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7. 
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [21]:
b = np.arange(20, 1, -2).reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [22]:
a.ndim, b.ndim

(1, 2)

##### Ответ: a - одномерный, b - двумерный массивы.

#### 8. 
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [23]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [24]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [25]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
v.size

10

#### 9.
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy),
состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A.
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.
Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и
почему?

In [27]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [30]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [31]:
B.shape

(4, 4)

In [32]:
d = np.linalg.det(B)
d

0.0

##### Ответ: Матрица B квадратная, но определитель d == 0, поэтому обратную матрицу вычислить не получится.

#### 10. 
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [33]:
np.random.seed(42)

#### 11. 
Создайте одномерный массив c, составленный из последовательности 16-ти случайных
равномерно распределенных целых чисел от 0 до 16 невключительно.

In [34]:
np.random.seed(42)
c = np.random.permutation(16)
c

array([ 0,  1,  5, 14, 13, 11,  8,  9,  2, 15,  4,  7, 10, 12,  3,  6])

#### 12. 
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D,
поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [35]:
C = c.reshape(4, 4)
C

array([[ 0,  1,  5, 14],
       [13, 11,  8,  9],
       [ 2, 15,  4,  7],
       [10, 12,  3,  6]])

In [36]:
D = np.add(C * 10, B)
D

array([[  5,  24,  73, 172],
       [144, 160, 166, 212],
       [ 43, 236, 189, 282],
       [132, 242, 242, 362]])

In [37]:
np.linalg.det(D)

8045799.999999932

In [38]:
np.linalg.matrix_rank(D)

4

In [39]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.05146536, -0.0877203 , -0.06485371,  0.12634667],
       [-0.06679013, -0.11426086, -0.06294216,  0.14768202],
       [ 0.19167765,  0.36821447,  0.22556365, -0.4824281 ],
       [-0.06472197, -0.13778369, -0.0850655 ,  0.1804718 ]])

#### 13. 
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице.
Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции
numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве
источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых
соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему
элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы
D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [40]:
D_inv[D_inv < 0] = 0
D_inv[D_inv > 0] = 1
D_inv

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
E = np.zeros((4, 4))
E[np.where(D_inv == 1)] = B[np.where(D_inv == 1)]
E[np.where(D_inv == 0)] = C[np.where(D_inv == 0)]
E

array([[  0.,   1.,   5.,  32.],
       [ 13.,  11.,   8., 122.],
       [ 23.,  86., 149.,   7.],
       [ 10.,  12.,   3., 302.]])